"""empty message

Revision ID: 0618a0517021
Revises: d1859e7c3617
Create Date: 2021-07-15 12:38:05.772677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0618a0517021"
down_revision = "d1859e7c3617"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track_singers", sa.Column("created_timestamp", sa.DateTime(), nullable=False)
    )
    op.add_column("track_singers", sa.Column("singer_id", sa.Integer(), nullable=False))
    op.add_column("track_singers", sa.Column("track_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        "track_singers_Track_id_fkey", "track_singers", type_="foreignkey"
    )
    op.drop_constraint(
        "track_singers_Singer_id_fkey", "track_singers", type_="foreignkey"
    )
    op.create_foreign_key(None, "track_singers", "track", ["track_id"], ["id"])
    op.create_foreign_key(None, "track_singers", "singer", ["singer_id"], ["id"])
    op.drop_column("track_singers", "Track_id")
    op.drop_column("track_singers", "Singer_id")
    op.drop_column("track_singers", "create_timestamp")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track_singers",
        sa.Column(
            "create_timestamp",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "track_singers",
        sa.Column("Singer_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "track_singers",
        sa.Column("Track_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "track_singers", type_="foreignkey")
    op.drop_constraint(None, "track_singers", type_="foreignkey")
    op.create_foreign_key(
        "track_singers_Singer_id_fkey", "track_singers", "singer", ["Singer_id"], ["id"]
    )
    op.create_foreign_key(
        "track_singers_Track_id_fkey", "track_singers", "track", ["Track_id"], ["id"]
    )
    op.drop_column("track_singers", "track_id")
    op.drop_column("track_singers", "singer_id")
    op.drop_column("track_singers", "created_timestamp")
    # ### end Alembic commands ###
