"""empty message

Revision ID: 573cc162db15
Revises: 8be737ccc900
Create Date: 2021-07-06 10:20:51.679264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573cc162db15'
down_revision = '8be737ccc900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('singer', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('track', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('translation', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_date')
    op.drop_column('translation', 'created_date')
    op.drop_column('track', 'created_date')
    op.drop_column('singer', 'created_date')
    # ### end Alembic commands ###
