"""empty message

Revision ID: 5fb3935a3425
Revises: c59645154059
Create Date: 2021-07-07 18:38:38.891491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5fb3935a3425"
down_revision = "c59645154059"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track", sa.Column("file", sa.LargeBinary(), nullable=True))
    op.create_unique_constraint(None, "translation", ["track_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "translation", type_="unique")
    op.drop_column("track", "file")
    # ### end Alembic commands ###
