"""empty message

Revision ID: b4258fa48c14
Revises: 
Create Date: 2021-07-13 11:45:39.447659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4258fa48c14"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column(
            "update_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("password", sa.String(length=200), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "singer",
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column(
            "update_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "track",
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column(
            "update_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("original_language", sa.String(length=2), nullable=False),
        sa.Column("singer_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["singer_id"],
            ["singer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "track_singers",
        sa.Column("Singer_id", sa.Integer(), nullable=True),
        sa.Column("Track_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Singer_id"],
            ["singer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["Track_id"],
            ["track.id"],
        ),
    )
    op.create_table(
        "translation",
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column(
            "update_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("language", sa.CHAR(length=2), nullable=False),
        sa.Column("auto_translate", sa.Boolean(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translation")
    op.drop_table("track_singers")
    op.drop_table("track")
    op.drop_table("singer")
    op.drop_table("user")
    # ### end Alembic commands ###
