"""add nullable attribute

Revision ID: bb1650639b58
Revises: 4c386d5f874c
Create Date: 2021-07-08 16:11:47.998730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bb1650639b58"
down_revision = "4c386d5f874c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "singer", "created_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "singer",
        "update_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "singer", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "track", "created_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "track",
        "update_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "track", "name", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    op.alter_column("track", "text", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "track", "original_language", existing_type=sa.VARCHAR(length=2), nullable=False
    )
    op.drop_column("track", "file")
    op.alter_column(
        "translation",
        "created_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "translation",
        "update_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("translation", "text", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "translation", "language", existing_type=sa.CHAR(length=2), nullable=False
    )
    op.alter_column(
        "user", "created_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "user",
        "update_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user", "public_id", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.alter_column(
        "user", "name", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.alter_column(
        "user", "password", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "password", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.alter_column("user", "name", existing_type=sa.VARCHAR(length=200), nullable=True)
    op.alter_column(
        "user", "public_id", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.alter_column(
        "user",
        "update_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user", "created_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "translation", "language", existing_type=sa.CHAR(length=2), nullable=True
    )
    op.alter_column("translation", "text", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "translation",
        "update_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "translation",
        "created_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.add_column(
        "track",
        sa.Column("file", postgresql.BYTEA(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "track", "original_language", existing_type=sa.VARCHAR(length=2), nullable=True
    )
    op.alter_column("track", "text", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("track", "name", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.alter_column(
        "track",
        "update_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "track", "created_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "singer", "name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "singer",
        "update_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "singer", "created_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
