"""empty message

Revision ID: ee9cef170a5a
Revises: 573cc162db15
Create Date: 2021-07-06 10:27:52.598345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9cef170a5a'
down_revision = '573cc162db15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('singer', sa.Column('updatetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('track', sa.Column('updatetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('translation', sa.Column('updatetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updatetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updatetime')
    op.drop_column('translation', 'updatetime')
    op.drop_column('track', 'updatetime')
    op.drop_column('singer', 'updatetime')
    # ### end Alembic commands ###
